### ISSUE TITLE
Installing monorepolint does not install the binary with PNPM

### ISSUE THREAD

**Issue by adidahiya** [monorepolint/monorepolint#194]
I have a small tooling package with a few dependencies:

```
    "dependencies": {
        "monorepolint": "^0.5.0-alpha.96",
        "semver": "^7.3.7",
        "ts-morph": "^15.1.0",
        "typescript": "4.7.4"
    }
```

When I run `pnpm install`, the following modules are installed:

<img width="387" alt="image" src="https://user-images.githubusercontent.com/723999/190449002-6b3062a2-0a03-409f-84ec-8e38c75bb5ef.png">

As you can see there is no `node_modules/.bin/monorepolint` or `node_modules/.bin/mrl` executable.

I expected installing the `monorepolint` package to include this executable, without having to know about `@monorepolint/cli` directly. If that's not the case, I think the README should be updated to reflect that.

**Comment by ericanderson** [comment]
Ah this sadly makes sense given pnpm doesn't hoist. I am unsure of the "correct" way to do this given the non hoisting. 

Do you have ideas?

**Comment by ericanderson** [comment]
keep open

**Comment by adidahiya** [comment]
keep open please
